#! /usr/bin/env python3

from collections import namedtuple
from cyclotron import Component
from cyclotron_aio.runner import run
import deep_speaker.train as train
import deep_speaker.training.scheduler as scheduler

import cyclotron_std.sys.argv as argv
import cyclotron_std.io.file as file
import cyclotron_std.logging as logging
import cyclotron_aio.stop as stop

TrainDrivers = namedtuple('TrainDrivers', [
    'scheduler', 'logging', 'file', 'argv', 'stop'
])


def main():
    run(
        Component(call=train.train, input=train.Source),
        TrainDrivers(
            scheduler=scheduler.make_driver(),
            logging=logging.make_driver(),
            file=file.make_driver(),
            argv=argv.make_driver(),
            stop=stop.make_driver(),
        ))


main()
